import sys
import os
import asyncio
import json


sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from mcp import ClientSession
from mcp.client.stdio import stdio_client
from tools.mcp_client import SERVER_PARAMS, navigate, get_snapshot
from orchestration.state import initiate_state
from nodes.planner import planner_node



USER_TASK = "Search for 'Playwright web automation' on Google and choose result"

SAAS_CONTEXT = """
Google Search is a web search engine.
The home page has a search bar in the center.
You type your query and press Enter or click the 'Google Search' button.
Results appear on the next page as a list of links.
"""




async def test_planner():
    

    async with stdio_client(SERVER_PARAMS) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()
            print("\n MCP server connected")

            # Step 1: Navigate to Google
            await navigate(session, "https://www.google.com")
            print("Navigated to Google")

            # Step 2: Get the accessibility tree of the current page
            snapshot = await get_snapshot(session)
            print("Accessibility tree captured")
            
            print(snapshot[:800])
            print("...")

            # Step 3: Build the state
            state = initiate_state(
                user_task=USER_TASK,
                saas_context=SAAS_CONTEXT
            )
            # Inject the snapshot as if the Actor had just navigated
            state["snapshot"] = snapshot

            print("\ Calling Planner agent...")
            print(f"    Task: {USER_TASK}")

            # Step 4: Call the Planner
            result = await planner_node(state)

            # Step 5: Display the plan
            plan = result.get("current_plan", [])

          
            if not plan:
                print("No plan generated by the Planner.")
            else:
                for step in plan:
                    print(f"\n  Step {step.get('step', '?')} — {step.get('description', '')}")
                    print(f"    Tool      : {step.get('tool', '')}")
                    print(f"    Arguments : {json.dumps(step.get('arguments', {}), indent=14)}")


            input("Browser is open. Press Enter to close it...")


if __name__ == "__main__":
    asyncio.run(test_planner())
