from typing import TypedDict, Dict, Any, Optional



class SharedState(TypedDict):
    # Task context (fixed at start)
    user_task:    str
    saas_context: str

    # Hierarchical Planning
    subgoals:              list[dict]    # List of subgoals generated by High-Level Planner
    current_subgoal_index: int           # Index of the currently active subgoal
    task_status:           str           # "pending", "in_progress", "completed", "failed"

    # Browser state
    current_url:     str
    snapshot_before: Optional[str]
    snapshot_after:  Optional[str]

    # Current step — 1 step at a time from the Planner
    current_step: Optional[Dict]   # {"tool": ..., "arguments": ..., "description": ...}

    # Results
    last_action_result:   Optional[str]
    last_action_is_error: bool          # True if the Actor got a technical error from MCP
    step_done:            bool          # set by Validator
    memory:               list[dict]    # history of steps and validator feedback

    # Termination
    error:     Optional[str]


def initiate_state(user_task: str, saas_context: str) -> SharedState:
    return SharedState(
        user_task=user_task,
        saas_context=saas_context,
        
        subgoals=[],
        current_subgoal_index=0,
        task_status="pending",

        current_url="",
        snapshot_before=None,
        snapshot_after=None,

        current_step=None,

        last_action_result=None,
        last_action_is_error=False,
        step_done=False,
        memory=[],

        error=None
    )