from typing import TypedDict, Dict, Any, Optional


class SharedState(TypedDict):
    # Task context 
    user_task:    str
    saas_context: str
    channel:      Any 

    # Hierarchical Planning
    subgoals:              list[dict]    # List of subgoals generated by High-Level Planner
    current_subgoal_index: int           # Index of the currently active subgoal
    task_status:           str           # "pending", "in_progress", "completed", "failed"

    # Browser state
    current_url:     str
    snapshot_before: Optional[str]
    snapshot_after:  Optional[str]

    
    current_step: Optional[Dict]   
    # Results
    last_action_result:   Optional[str]
    last_action_is_error: bool
    step_done:            bool
    memory:               list[dict]

    # ask_user — pause pipeline to request missing info from user
    pending_question: Optional[str] 
    user_answer:      Optional[str]   

    # Termination
    error:     Optional[str]


def initiate_state(user_task: str, saas_context: str, channel=None) -> SharedState:
    return SharedState(
        user_task=user_task,
        saas_context=saas_context,
        channel=channel,

        subgoals=[],
        current_subgoal_index=0,
        task_status="pending",

        current_url="",
        snapshot_before=None,
        snapshot_after=None,

        current_step=None,

        last_action_result=None,
        last_action_is_error=False,
        step_done=False,
        memory=[],

        pending_question=None,
        user_answer=None,

        error=None
    )